version: "3.8"

services:
  web:
    image: traefik/whoami:v1.10
    networks:
      - appnet
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: ingress
    deploy:
      replicas: 4
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 2s
        order: start-first
      placement:
        max_replicas_per_node: 2

networks:
  appnet:
    driver: overlay
    attachable: true
